import {
  BarChart3,
  Calendar,
  Camera,
  CloudSun,
  Download,
  Eye,
  Layers,
  Palette,
  Search,
  Shield,
  Shirt,
  Sparkles,
  Tags,
  User,
  Wand2,
} from 'lucide-react'
import type { FeaturePageTemplateProps } from '@/components/landing/FeaturePageTemplate'

const related = [
  { title: 'Wardrobe extraction', description: 'Turn clothing photos into reviewable wardrobe items.', href: '/features/ai-wardrobe-extraction' },
  { title: 'Daily outfits', description: 'Use your closet, day, and preferences to guide a look.', href: '/features/outfit-recommendations' },
  { title: 'Wardrobe analytics', description: 'Find patterns in what you own and wear.', href: '/features/wardrobe-analytics' },
]

export const featurePages: Record<string, FeaturePageTemplateProps> = {
  wardrobeExtraction: {
    title: 'AI Wardrobe Extraction',
    description: 'Photograph clothes, review the details FitCheck finds, and save a wardrobe you can browse and use.',
    canonicalPath: '/features/ai-wardrobe-extraction',
    keywords: 'AI wardrobe extraction, digital closet, clothing catalog',
    eyebrow: 'Digital wardrobe',
    stats: [
      { value: '50–400', label: 'AI item extractions/month (Free → Pro)' },
      { value: 'Multi-item', label: 'Photos supported in one upload' },
      { value: 'Review first', label: 'AI details are drafts until you approve' },
    ],
    heroImage: '/landing/flatlay.webp',
    heroImageSrcSet: '/landing/flatlay-640.webp 640w, /landing/flatlay.webp 1024w',
    heroImageAlt: 'Clothing arranged in a flat lay for wardrobe cataloging',
    preparationTitle: 'Start with a photo you can review',
    preparation: ['Use clear lighting and include the whole garment where practical.', 'Upload a single piece, flat lay, or supported multi-item photo.', 'Keep the original while generated crops and item details are pending.'],
    features: [
      { icon: Camera, title: 'Photo-first capture', description: 'Begin from the image rather than a long manual form.' },
      { icon: Tags, title: 'Reviewable details', description: 'Check categories, color, and tags before an item is saved.' },
      { icon: Search, title: 'Searchable closet', description: 'Use the saved details to find and filter your pieces later.' },
      { icon: Shirt, title: 'Batch-friendly flow', description: 'Move from upload to review to saving without losing your place.' },
    ],
    steps: [
      { title: 'Capture', description: 'Add one or more clothing photos.' },
      { title: 'Process', description: 'See a clear queued or processing state while extraction runs.' },
      { title: 'Review', description: 'Adjust extracted details and resolve any issues.' },
      { title: 'Save', description: 'Add approved pieces to your wardrobe.' },
    ],
    contextTitle: 'A closet you can act on',
    contextDescription: 'Saved items become the foundation for browsing, outfit building, recommendations, and planning.',
    contextItems: ['Keep original photos available as reference.', 'Make corrections before saving, not after a batch disappears.', 'Use the next action: build an outfit or view your closet.'],
    relatedFeatures: related,
  },
  virtualTryOn: {
    title: 'Virtual Try-On',
    description: 'Use an avatar or photo and a selected outfit to generate a visual reference for your next look.',
    canonicalPath: '/features/virtual-try-on',
    keywords: 'AI virtual try-on, outfit visualization, wardrobe try-on',
    eyebrow: 'Visualize a look',
    stats: [
      { value: '50–1,000', label: 'Outfit visualizations/month (Free → Pro)' },
      { value: 'Your clothes', label: 'Try-on is built from your wardrobe' },
      { value: 'Reference', label: 'Output aids decisions, not fit guarantees' },
    ],
    heroImage: '/landing/outfit.webp',
    heroImageSrcSet: '/landing/outfit-640.webp 640w, /landing/outfit.webp 864w',
    heroImageAlt: 'Complete outfit arranged ready to wear',
    preparationTitle: 'Set up a useful try-on',
    preparation: ['Choose an avatar or upload a suitable reference photo.', 'Select the garments or outfit you want to visualize.', 'Treat output as a visual reference, not a fit or sizing guarantee.'],
    features: [
      { icon: User, title: 'Avatar or photo input', description: 'Use an existing setup or complete it without losing the selected outfit.' },
      { icon: Layers, title: 'Outfit context', description: 'Start from pieces and looks already in your wardrobe.' },
      { icon: Eye, title: 'Result comparison', description: 'Keep the source and result visible together for a clearer decision.' },
      { icon: Shield, title: 'Clear recovery', description: 'Retry, change inputs, or leave setup for later when generation cannot finish.' },
    ],
    steps: [
      { title: 'Choose a person', description: 'Select an avatar or add a reference photo.' },
      { title: 'Choose a look', description: 'Pick an outfit or the pieces to use.' },
      { title: 'Generate', description: 'Follow elapsed, opaque processing status rather than a made-up percentage.' },
      { title: 'Decide', description: 'Compare, retry, download, or return to the outfit.' },
    ],
    contextTitle: 'A decision-support view',
    contextDescription: 'Try-on is most useful when it helps you choose among looks you already own or are considering.',
    contextItems: ['Compare input and result side by side.', 'Save a useful result or retry with better inputs.', 'Continue to outfit planning when you have your answer.'],
    relatedFeatures: [related[0], related[1], { title: 'AI photoshoot', description: 'Create images with a selected style and controlled download actions.', href: '/features/ai-photoshoot-generator' }],
  },
  photoshoot: {
    title: 'AI Photoshoot Generator',
    description: 'Choose a style, provide consented reference photos, and generate images with an explicit result and recovery flow.',
    canonicalPath: '/features/ai-photoshoot-generator',
    keywords: 'AI photoshoot generator, AI profile photo, AI headshot',
    eyebrow: 'Generate a photoshoot',
    stats: [
      { value: '10–50', label: 'Photoshoot images/day (Free → Pro)' },
      { value: '1 selfie', label: 'Starting input for a studio-style set' },
      { value: '3+', label: 'Use cases: LinkedIn, dating, social' },
    ],
    heroImage: '/landing/outfit.webp',
    heroImageSrcSet: '/landing/outfit-640.webp 640w, /landing/outfit.webp 864w',
    heroImageAlt: 'Styled outfit photographed against a neutral surface',
    preparationTitle: 'Choose the result you need',
    preparation: ['Select a use case or style before starting generation.', 'Only upload photos you have permission to use.', 'Review availability and usage limits in the product before starting.'],
    features: [
      { icon: Palette, title: 'Style selection', description: 'Start with the context for the image: professional, social, or another use.' },
      { icon: Shield, title: 'Consent-aware input', description: 'Make the photo and permissions step explicit before generation.' },
      { icon: Sparkles, title: 'Truthful generation state', description: 'Queued and processing states communicate work without false estimates.' },
      { icon: Download, title: 'Clear results', description: 'Download, retry, or select another result when generation completes.' },
    ],
    steps: [
      { title: 'Upload', description: 'Add reference photos that meet the visible guidance.' },
      { title: 'Configure', description: 'Choose style and any supported controls.' },
      { title: 'Generate', description: 'Follow actual queued or processing status.' },
      { title: 'Use the result', description: 'Download, retry, or return to choose a different style.' },
    ],
    contextTitle: 'A result with ownership actions',
    contextDescription: 'The result view makes the generated image, download action, and recovery paths equally easy to find.',
    contextItems: ['Keep partial failures attached to their specific input.', 'Retry only what needs another attempt.', 'Check product limits before beginning another generation.'],
    relatedFeatures: [related[0], related[1], { title: 'Virtual try-on', description: 'Visualize a selected outfit on an avatar or reference photo.', href: '/features/virtual-try-on' }],
  },
  recommendations: {
    title: 'Outfit Recommendations',
    description: 'Start with the day, then use weather, occasion, and your wardrobe to guide a practical outfit choice.',
    canonicalPath: '/features/outfit-recommendations',
    keywords: 'AI outfit recommendations, what to wear today, weather outfit planner',
    eyebrow: 'What to wear today',
    stats: [
      { value: 'Weather + calendar', label: 'Context the recommendations use' },
      { value: 'Your items', label: 'Looks come from your real wardrobe' },
      { value: '50–1,000', label: 'Visualizations/month (Free → Pro)' },
    ],
    heroImage: '/landing/outfit.webp',
    heroImageSrcSet: '/landing/outfit-640.webp 640w, /landing/outfit.webp 864w',
    heroImageAlt: 'Complete everyday outfit laid out for planning',
    preparationTitle: 'Put the day first',
    preparation: ['Confirm the occasion and weather context where it is available.', 'Use a wardrobe with enough saved pieces for meaningful choices.', 'Keep one next action visible: save, plan, or find matches.'],
    features: [
      { icon: CloudSun, title: 'Daily context', description: 'Start with weather and occasion rather than a generic list of outfits.' },
      { icon: Shirt, title: 'Your wardrobe coverage', description: 'Make clear which saved pieces are available for the recommendation.' },
      { icon: Wand2, title: 'Why this look', description: 'Show the explanation alongside a recommended outfit.' },
      { icon: Calendar, title: 'Plan it', description: 'Save the look or assign it to a day when you are ready.' },
    ],
    steps: [
      { title: 'Set the context', description: 'Choose the day, occasion, and relevant conditions.' },
      { title: 'Get a look', description: 'Review a recommendation drawn from available wardrobe pieces.' },
      { title: 'Understand it', description: 'Read the contextual explanation before deciding.' },
      { title: 'Save or plan', description: 'Favorite the look or assign it to your calendar.' },
    ],
    contextTitle: 'One recommendation, one decision',
    contextDescription: 'A useful recommendation is not just an image: it explains the context and makes the next action immediate.',
    contextItems: ['Daily Weather, Complete Look, Find Matches, Shopping, and Astrology remain distinct tools.', 'Use an explicit empty state when wardrobe coverage is low.', 'Save the selected result to return to it later.'],
    relatedFeatures: [related[0], related[2], { title: 'Virtual try-on', description: 'Use a try-on view when you need another visual reference.', href: '/features/virtual-try-on' }],
  },
  analytics: {
    title: 'Wardrobe Analytics',
    description: 'Use real wear and wardrobe data to understand the pieces you reach for and the ones you may revisit.',
    canonicalPath: '/features/wardrobe-analytics',
    keywords: 'wardrobe analytics, cost per wear, clothing wear tracking',
    eyebrow: 'Wear data, clearly explained',
    stats: [
      { value: 'Price ÷ wears', label: 'Cost-per-wear computed per item' },
      { value: 'Wear log', label: 'Tracked from the outfits you record' },
      { value: 'Utilization', label: 'See what you wear — and what you skip' },
    ],
    heroImage: '/landing/flatlay.webp',
    heroImageSrcSet: '/landing/flatlay-640.webp 640w, /landing/flatlay.webp 1024w',
    heroImageAlt: 'Wardrobe items arranged for cataloging and review',
    preparationTitle: 'Start from information you control',
    preparation: ['Add purchase information only when it is useful to you.', 'Log or plan wears to build a meaningful history.', 'Read charts with a table or plain-language fallback where available.'],
    features: [
      { icon: BarChart3, title: 'Wear patterns', description: 'See available history and usage patterns from the data you record.' },
      { icon: Calendar, title: 'Planning history', description: 'Connect saved or planned outfits to a clearer view of wardrobe use.' },
      { icon: Tags, title: 'Item context', description: 'Compare categories, colors, and other saved details without losing the item itself.' },
      { icon: Search, title: 'Actionable review', description: 'Move from an observation to the item, outfit, or next planning action.' },
    ],
    steps: [
      { title: 'Build the closet', description: 'Save the items you want to understand.' },
      { title: 'Record context', description: 'Add wear, plan, or purchase details when available.' },
      { title: 'Review patterns', description: 'Use accessible summaries and charts to look for signals.' },
      { title: 'Act on it', description: 'Rewear, plan, edit, or shop with a specific reason.' },
    ],
    contextTitle: 'Insights are not promises',
    contextDescription: 'Analytics should explain the data available in your account, not guarantee a particular savings or utilization outcome.',
    contextItems: ['Use a table fallback for chart information.', 'Label unavailable or incomplete data plainly.', 'Return to a source item when a pattern needs review.'],
    relatedFeatures: [related[0], related[1], { title: 'Outfit recommendations', description: 'Turn wardrobe availability into a choice for the day.', href: '/features/outfit-recommendations' }],
  },
}
